#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
echo "Set IP Address"
while read paraa parab   
do    
	if [ $paraa = 'IP' ]; then   
		ifconfig eth0 $parab
	break
	fi
done < /etc/clyy.conf
# Start a new shell in the console
echo "Starting mdev......"
mount -n -t proc none /proc
mount -t tmpfs mdev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts
mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
echo "mount all"
mount -a
echo "*********************************************************"
echo "     clyy                "
echo "   Wellcome  ! !         "
echo "********************************************************"
